### ISSUE TITLE
AsyncStackTracerExample

### ISSUE THREAD

**Issue by idkjs** [mrmurphy/serbet#2]
Thanks for sharing this project.

2 Questions. How is expected that we run this? I tried installing from git but could not get bucklescript to find the module whether I had it in `bsconfig.json` or not. There is something I am missing but not sure what.

Second, after copying the source files into a repo, the stack trace example threw a few errors. I worked through them and came up with [this working gist https://gist.github.com/idkjs/7fed94ad7e82e742abbfc18770b2ca02 ](https://gist.github.com/idkjs/7fed94ad7e82e742abbfc18770b2ca02) which runs and doesn't error out but I am not sure its doing what you intended. 

Or maybe I just didn't have it setup right and this was unnecessary. Any feedback would be appreciated. Thank you, sir.

this is the first error:

```
  21 │ open Handler;
  22 │ module Endpoint =
  23 │   Handler.Make({
  24 │     let path = "/";
   . │ ...
  31 │     };
  32 │   });
  33 │
  34 │ let app = Express.App.make();

  Signature mismatch:
  Modules do not match:
    {
      let path: string;
      let verb: AsyncAwait.Handler.verb;
      let handler: 'a => Js.Promise.t(AsyncAwait.Handler.res);
    }
  is not included in
    AsyncAwait.Handler.AppCfg
  The value `app' is required but not provided
  File "/Users/prisc_000/Downloads/egghead-reasonml-async-await-graphql/src/serbert/Handler.re", line 130, characters 22-44:
    Expected declaration

FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)
```

Fixed by adding `module App` and passing it to `module Endpoint`

```
module App =
  Server.Make({});

module Endpoint =
  Handler.Make(
    App,{
    let path = "/";
    let verb = GET;
    let handler = _req => {
      let%Async user = newUser();
      let%Async user2 = processUser(user);
      let%Async _ = saveUserInDatabase(user2);
      async @@ OkString("Done");
    };
  });
```

Once you fix that, you get the following error:
```
  38 │ let app = Express.App.make();
  39 │ let router = Express.Router.make();
  40 │ router->Endpoint.use;
  41 │
  42 │ app->Express.App.useRouter(router);

  The value use can't be found in Endpoint

FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)
```

Fixed here:
```
// router->Endpoint.use;
// change router call to `Express.Router.use` and pass it `Endpoint.expressHandler` which is exposed on `MakeWithCustomMiddleware` module in `Handler.re`
router->Express.Router.use(Endpoint.expressHandler);
```

Not sure if this correct.

**Comment by mrmurphy** [comment]
So sorry about that @idkjs . I've updated the example and added a comment. Try again?

**Comment by mrmurphy** [comment]
@idkjs I just pushed an update with docs that are a bit better, and a different namespace for the server module entirely. I'd love your feedback. Please let me know if you're able to figure out what to do with just the source and the sparse docs, or if you need more to get going.

**Comment by idkjs** [comment]
@mrmurphy I went ahead and applied your updates. I tried installing from git but could not get bucklescript to find the `Serbert` module whether I had it in bsconfig.json or not. There is something I am missing but not sure what. I copied the source files into a test repo to test.

Regarding the stack trace example. It doesn't work as is in the repo below. I got it to work by making the changes in the original post and accounting for the file name changes.

Here is a repo with the working stacktrace file: https://github.com/idkjs/AsyncStackTraceExample/blob/master/src/AsyncStackTraceExample.re and the as is file which doesn't work here: https://github.com/idkjs/AsyncStackTraceExample/blob/master/src/ErrorAsyncStackTraceExample.re. 

I hope this feedback helps. Many Bothans died to bring you this information.

**Comment by mrmurphy** [comment]
When you say you're installing from git, how exactly do you mean? I'm expecting that you're doing `npm install --save sorbet@0.2.0` inside of your own project, and then adding `serbet` into your bs-dependencies. At that point you should be able to copy the contents of https://github.com/mrmurphy/serbet/blob/master/Examples/AsyncStackTraceExample.re into a file in your project and it should compile for you. Is that what's going on for you?

**Comment by idkjs** [comment]
Didnt work from git when i tried it before. Works now. Works the same as noted in previous comments. The AsynStackTraceExample in test repo doesnt work. This is just to help out in the small way I can. I do not need this for anything. FYI!

**Comment by mrmurphy** [comment]
Oh I'm sorry, I feel so dumb. I didn't update the example properly, and I only looked at your example file, not the repo. 

This should be the fixed version! Thank you!
https://github.com/mrmurphy/serbet/blob/master/Examples/AsyncStackTraceExample.re
