### ISSUE TITLE
Use Fastify ?

### ISSUE THREAD

**Issue by tlvenn** [mrmurphy/serbet#3]
Hi,

Thanks a lot for this project, I was wondering if you had considered using Fastify instead of Express ?
> https://github.com/fastify/benchmarks/

**Comment by mrmurphy** [comment]
Thanks for the suggestion @tlvenn! I've read up a bit on Fastify before, but never tried it out. If you're interesting in forking the project and changing it to fastify I'd be interested in checking it out!

**Comment by tlvenn** [comment]
Thanks @mrmurphy, i was merely curious if it is something you had considered and I totally understand that given the fragmentation of http servers / frameworks, it is sensible to pick the most used one.

**Comment by mrmurphy** [comment]
Thanks for being interested!
