### ISSUE TITLE
Create documentation friendles

### ISSUE THREAD

**Issue by enieber** [mrmurphy/serbet#6]
Why no create the documentation more friends with examples and the context of use. I need a long time to understand the code, so I write the some samples [how to use the Serbet](https://github.com/enieber/reason-serbet-helper-doc).

**Comment by mrmurphy** [comment]
Wow, awesome @enieber, thank you! I'm sorry I didn't see this issue before. I just wrote a while new version of Serbet that I"ll be releasing sometime next week, I think, with much better documentation.

**Comment by enieber** [comment]
@mrmurphy when you release new version of Serbet put in [re-newsletter](https://github.com/enieber/re-newsletter)  please

**Comment by mrmurphy** [comment]
Great idea!
